Repository muriloalvesdev/thehero-backend, pull requests merged in 2020-11, with the labels that each got.

#36 [FEATURE] - Implementar swagger
  pom.xml
  src/main/java/br/com/thehero/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: feature

#33 Adicionando padrão generics e otimizando métodos
  src/main/java/br/com/thehero/controller/authentication/AuthenticationController.java
  src/main/java/br/com/thehero/controller/file/FileController.java
  src/main/java/br/com/thehero/controller/handler/HandlerException.java
  src/main/java/br/com/thehero/controller/incidents/IncidentsController.java
  src/main/java/br/com/thehero/controller/logout/LogoutController.java
  src/main/java/br/com/thehero/controller/organization/OrganizationController.java
  src/main/java/br/com/thehero/controller/profile/Profile.java
  src/main/java/br/com/thehero/dto/IncidentsDTO.java
  src/main/java/br/com/thehero/dto/OrganizationDTO.java
  src/main/java/br/com/thehero/dto/UserDTO.java
  src/main/java/br/com/thehero/login/config/SimpleCORSFilter.java
  src/main/java/br/com/thehero/login/config/jwt/JwtAuthEntryPoint.java
  src/main/java/br/com/thehero/login/config/jwt/JwtBlacklist.java
  src/main/java/br/com/thehero/login/exception/ArgumentInvalidException.java
  src/main/java/br/com/thehero/login/exception/EmailNotFoundException.java
  src/main/java/br/com/thehero/login/exception/ExistingEmailException.java
  src/main/java/br/com/thehero/login/exception/IllegalArgumentException.java
  src/main/java/br/com/thehero/login/exception/IllegalRoleException.java
  src/main/java/br/com/thehero/login/exception/Sha512Exception.java
  src/main/java/br/com/thehero/login/exception/TokenInvalidException.java
  src/main/java/br/com/thehero/login/exception/TokenNotFoundException.java
  src/main/java/br/com/thehero/login/exception/UserIdNotFoundException.java
  src/main/java/br/com/thehero/login/request/RegisterDTO.java
  src/main/java/br/com/thehero/login/service/UserDetailsServiceImpl.java
  src/main/java/br/com/thehero/service/convert/IncidentsConvert.java
  src/main/java/br/com/thehero/service/convert/OrganizationConvert.java
  src/main/java/br/com/thehero/service/file/FilesService.java
  src/main/java/br/com/thehero/service/file/impl/FilesServiceImpl.java
  src/main/java/br/com/thehero/service/incidents/IncidentsService.java
  src/main/java/br/com/thehero/service/incidents/impl/IncidentsServiceImpl.java
  src/main/java/br/com/thehero/service/organization/OrganizationService.java
  src/main/java/br/com/thehero/service/organization/impl/OrganizationServiceImpl.java
  src/main/java/br/com/thehero/service/profile/ProfileService.java
  src/main/java/br/com/thehero/service/profile/impl/ProfileServiceImpl.java
  src/test/java/br/com/thehero/service/convert/IncidentsConvertTest.java
  src/test/java/br/com/thehero/service/file/impl/FilesServiceImplTest.java
Labels: enhancement

#37 [EH] Alterando LOGs para utilizar apenas o Lombok @Slf4j
  src/main/java/br/com/thehero/controller/handler/HandlerException.java
  src/main/java/br/com/thehero/exception/ArgumentInvalidException.java
  src/main/java/br/com/thehero/exception/EmailNotFoundException.java
  src/main/java/br/com/thehero/exception/ExistingEmailException.java
  src/main/java/br/com/thehero/exception/IllegalArgumentException.java
  src/main/java/br/com/thehero/exception/IllegalRoleException.java
  src/main/java/br/com/thehero/exception/IncidentNotFoundException.java
  src/main/java/br/com/thehero/exception/Sha512Exception.java
  src/main/java/br/com/thehero/exception/TokenInvalidException.java
  src/main/java/br/com/thehero/exception/TokenNotFoundException.java
  src/main/java/br/com/thehero/exception/UserIdNotFoundException.java
  src/main/java/br/com/thehero/login/config/SimpleCORSFilter.java
  src/main/java/br/com/thehero/login/config/jwt/JwtAuthEntryPoint.java
  src/main/java/br/com/thehero/login/config/jwt/JwtBlacklist.java
  src/main/java/br/com/thehero/login/config/jwt/JwtProvider.java
  src/main/java/br/com/thehero/login/service/UserDetailsServiceImpl.java
  src/main/java/br/com/thehero/login/service/UserService.java
  src/main/java/br/com/thehero/login/util/Utils.java
  src/main/java/br/com/thehero/service/file/impl/FilesServiceImpl.java
  src/test/java/br/com/thehero/service/file/impl/FilesServiceImplTest.java
Labels: enhancement

#39 [BUG] Corrigindo nome dos atributos json do incidentsDTO
  src/main/java/br/com/thehero/dto/IncidentsDTO.java
  src/main/java/br/com/thehero/dto/OrganizationDTO.java
Labels: bug
